modelname   : NA
modelcomment: >
    NAComment. 
baseurl     : /NA
accountname : VicCastillo
preurl      : https://github.com/VicCastillo
#
gems:
  - jekyll-sitemap
markdown: redcarpet
exclude:  ['NIL']
encoding: UTF-8

