modelname   : STEM-Dev
modelcomment: Developing STEM resources
baseurl     : 
accountname : VicCastillo
preurl      : https://github.com/STEM-Dev
#
gems:
  - jekyll-sitemap
markdown: redcarpet
exclude:  ['NIL']
encoding: UTF-8

